// Build-time bridge: reads the `gallery` Firestore collection via the
// Firebase Admin SDK and writes a static data file the Astro site can
// import at build time. No live server, no HTTP endpoint — matches this
// project's "static site, no SSR" non-goal for the gallery feature.
//
// Run automatically via the "prebuild" npm script before `astro build`.
// Safe to run manually too: `node scripts/fetch-gallery.mjs`.

import admin from 'firebase-admin';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Shared service account location — same path import_customers.js already
// uses for local Firebase Admin SDK auth, so there's only one secret file
// to keep out of git instead of a second copy under astro/.
const serviceAccountPath = path.join(
  __dirname,
  '..',
  '..',
  'firebase',
  'functions',
  'secrets',
  'serviceAccountKey.json'
);

/**
 * Pure transform from a Firestore gallery document to the shape
 * astro/src/data/gallery.js's GalleryPhoto typedef expects. No Firestore
 * calls here — this is what makes it unit-testable without a live/emulated
 * database.
 * @param {{ id: string, data: () => Record<string, any> }} doc
 * @returns {{ id: string, src: string, alt: string, caption: string|null, link: string|null }}
 */
export function docToGalleryPhoto(doc) {
  const data = doc.data();
  return {
    id: doc.id,
    src: data.imageUrl,
    alt: data.altText || '',
    caption: data.caption || null,
    link: data.link || null,
  };
}

async function main() {
  if (!admin.apps.length) {
    const config = {};
    if (fs.existsSync(serviceAccountPath)) {
      config.credential = admin.credential.cert(
        JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'))
      );
      console.log('Using local service account for gallery fetch.');
    } else {
      console.log('Using default credentials for gallery fetch.');
      config.credential = admin.credential.applicationDefault();
    }
    admin.initializeApp(config);
  }

  const db = admin.firestore();
  const snapshot = await db
    .collection('gallery')
    .where('isActive', '==', true)
    .orderBy('createdAt', 'desc')
    .get();

  const photos = snapshot.docs.map(docToGalleryPhoto);

  const outPath = path.join(__dirname, '..', 'src', 'data', 'syncedGallery.js');
  const contents =
    `// AUTO-GENERATED by scripts/fetch-gallery.mjs at build time. Do not edit by hand.\n` +
    `/** @type {import('./gallery.js').GalleryPhoto[]} */\n` +
    `export const galleryPhotos = ${JSON.stringify(photos, null, 2)};\n`;

  fs.writeFileSync(outPath, contents);
  console.log(`Wrote ${photos.length} gallery photo(s) to ${outPath}`);
}

// Only run when executed directly (e.g. `node scripts/fetch-gallery.mjs` or
// the "prebuild" npm script) — not when imported by tests, so importing
// docToGalleryPhoto never triggers a live Firestore connection attempt.
// Compares resolved filesystem paths (not raw URL strings) since
// import.meta.url uses forward slashes/percent-encoding while
// process.argv[1] uses the OS's native path format — a plain string
// comparison silently fails on Windows.
const isMainModule =
  process.argv[1] &&
  path.resolve(fileURLToPath(import.meta.url)) === path.resolve(process.argv[1]);

if (isMainModule) {
  main().catch((err) => {
    // Deliberately non-fatal: this runs as "prebuild" ahead of the full
    // site build (shop, events, home, checkout). A transient Firestore
    // hiccup here shouldn't take down the whole deploy — fall back to
    // whatever syncedGallery.js already exists (last successful fetch, or
    // the committed empty placeholder) and let the rest of the build
    // proceed. The error is still logged loudly so it doesn't go unnoticed.
    console.error('[fetch-gallery] Failed to fetch gallery photos from Firestore — build will continue with the existing syncedGallery.js data.');
    console.error(err);
  });
}
